name: dev
base: ubuntu@24.04

sdks:
    - name: openjdk
      channel: 17/stable

actions:
    prepare: bash hooks/prepare.sh
    test: bash hooks/execute.sh test
    start: bash hooks/execute.sh start
    buggy: bash hooks/execute.sh buggy
