name: dev
base: ubuntu@22.04

sdks:
    - name: openjdk
      channel: 17/stable

actions:
    prepare: bash hooks/prepare.sh

    unapplied: |
        javac src/Application.java -d out/
        java -cp out/ Application

    feature: |
        javac src/Application.java -d out/
        javac -XDignore.symbol.file --patch-module java.desktop=src/java.desktop src/java.desktop/sun/print/UnixPrintJob.java -d out/
        java --patch-module java.desktop=out -cp out/ Application
